# Generated by Django 3.1.7 on 2021-03-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
