# Generated by Django 3.1.7 on 2021-03-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_orders', '0003_auto_20210317_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
        ),
    ]
